### ISSUE TITLE
`shipyardctl create image` should not take -e flag

### ISSUE THREAD

**Issue by mpnally** [30x/shipyardctl#40]
The help says that `shipyardctl create image` accepts the -e flag to specify an environment. Environments are not meaningful for create image.

**Comment by noahdietz** [comment]
env vars during build should also be removed in `kiln` as well... 😃

**Comment by AdamMagaluk** [comment]
I think this is a no op on both the shipyardctl and kiln end. The shipyard environment is never provided or used by kiln. Shipyardctl uses the `-e KEY=VAL` for deployment environment variables but not to specify the shipyard environment.

The docs may be misleading because they say you can use `-e` to specify environment.

We could get rid of the shorthand `-e` and only allow `--env` to make it clearer.

**Comment by noahdietz** [comment]
I completely misread the original issue.

The `-e` flag is shorthand for `--env` like Adam said, but this is used to specify environment variables to be baked into the Docker image. We had talked about removing that functionality from `kiln`, so this flag should in fact be removed, but just want to make sure we are on the same page as to why it is being removed.

**Comment by noahdietz** [comment]
I was reminded that baking env vars into an image at build time was a desired feature in order to support "sane defaults" in application configurations. I'll change the verbiage on the flags so it is not confused with the Edge/Shipyard environment artifact...
